import { ThemePreset } from '../types/theme';

const baseTimestamp = Date.now();

export const themePresets: ThemePreset[] = [
  {
    id: 'light-default',
    name: 'Aurora Light',
    description: 'Bright, neutral palette optimized for daytime usage.',
    colors: {
      background: '#F7FAFC',
      backgroundSecondary: '#FFFFFF',
      backgroundTertiary: '#EDF2F7',
      text: '#1A202C',
      textSecondary: '#2D3748',
      textMuted: '#4A5568',
      primary: '#5A67D8',
      primaryHover: '#4C51BF',
      primaryActive: '#434190',
      accent: '#ED64A6',
      accentHover: '#D53F8C',
      success: '#38A169',
      warning: '#D69E2E',
      error: '#E53E3E',
      info: '#3182CE',
      border: '#CBD5E0',
      borderHover: '#A0AEC0',
      chartBullish: '#34D399',
      chartBearish: '#F87171',
      chartNeutral: '#A3BFFA',
      gradientStart: '#FFFFFF',
      gradientMiddle: '#C3DAFE',
      gradientEnd: '#FED7E2',
    },
  },
  {
    id: 'dark-default',
    name: 'Nebula Dark',
    description: 'High-contrast dark theme ideal for low-light environments.',
    colors: {
      background: '#0F172A',
      backgroundSecondary: '#131F3A',
      backgroundTertiary: '#1E293B',
      text: '#E2E8F0',
      textSecondary: '#CBD5F5',
      textMuted: '#94A3B8',
      primary: '#6366F1',
      primaryHover: '#4F46E5',
      primaryActive: '#4338CA',
      accent: '#F471B5',
      accentHover: '#EC4899',
      success: '#22C55E',
      warning: '#F97316',
      error: '#EF4444',
      info: '#38BDF8',
      border: '#1E293B',
      borderHover: '#334155',
      chartBullish: '#22C55E',
      chartBearish: '#F87171',
      chartNeutral: '#6366F1',
      gradientStart: '#0F172A',
      gradientMiddle: '#3B0764',
      gradientEnd: '#1E3A8A',
    },
  },
  {
    id: 'contrast-high',
    name: 'Supernova Contrast',
    description: 'Certified high contrast theme optimized for accessibility.',
    colors: {
      background: '#000000',
      backgroundSecondary: '#0D0D0D',
      backgroundTertiary: '#141414',
      text: '#FFFFFF',
      textSecondary: '#F5F5F5',
      textMuted: '#E0E0E0',
      primary: '#FFFF00',
      primaryHover: '#FFE600',
      primaryActive: '#FFD600',
      accent: '#00FFFF',
      accentHover: '#00E5FF',
      success: '#00FF00',
      warning: '#FFD700',
      error: '#FF3131',
      info: '#1E90FF',
      border: '#FFFFFF',
      borderHover: '#FFD700',
      chartBullish: '#00FF7F',
      chartBearish: '#FF4500',
      chartNeutral: '#00FFFF',
      gradientStart: '#000000',
      gradientMiddle: '#333333',
      gradientEnd: '#666666',
    },
  },
  {
    id: 'deep-sea',
    name: 'Deep Sea',
    description: 'Cool blues and teals inspired by ocean depths.',
    colors: {
      background: '#0C1927',
      backgroundSecondary: '#11283C',
      backgroundTertiary: '#173652',
      text: '#E2E8F0',
      textSecondary: '#ABC4D9',
      textMuted: '#7A94AD',
      primary: '#38BDF8',
      primaryHover: '#0EA5E9',
      primaryActive: '#0284C7',
      accent: '#2DD4BF',
      accentHover: '#14B8A6',
      success: '#34D399',
      warning: '#FACC15',
      error: '#F87171',
      info: '#22D3EE',
      border: '#1E3A5F',
      borderHover: '#2563EB',
      chartBullish: '#2DD4BF',
      chartBearish: '#F97316',
      chartNeutral: '#60A5FA',
      gradientStart: '#0C1927',
      gradientMiddle: '#164E63',
      gradientEnd: '#1E3A8A',
    },
  },
  {
    id: 'solar-flare',
    name: 'Solar Flare',
    description: 'Warm gradient-driven theme with vibrant accenting.',
    colors: {
      background: '#1A0F1F',
      backgroundSecondary: '#2D1435',
      backgroundTertiary: '#3C1A47',
      text: '#FDF2F8',
      textSecondary: '#FBCFE8',
      textMuted: '#F9A8D4',
      primary: '#F97316',
      primaryHover: '#EA580C',
      primaryActive: '#C2410C',
      accent: '#C026D3',
      accentHover: '#A21CAF',
      success: '#4ADE80',
      warning: '#FACC15',
      error: '#FB7185',
      info: '#67E8F9',
      border: '#4A1D5C',
      borderHover: '#701A75',
      chartBullish: '#F97316',
      chartBearish: '#FB7185',
      chartNeutral: '#C084FC',
      gradientStart: '#1A0F1F',
      gradientMiddle: '#581C87',
      gradientEnd: '#EA580C',
    },
  },
];

export const defaultThemePreset = themePresets[1];

export const DEFAULT_THEME_ID = defaultThemePreset.id;

export const createThemeFromPreset = (presetId: string) => {
  const basePreset = themePresets.find(preset => preset.id === presetId) ?? defaultThemePreset;
  return {
    id: `theme-${presetId}`,
    name: basePreset.name,
    colors: basePreset.colors,
    isCustom: false,
    createdAt: baseTimestamp,
    updatedAt: baseTimestamp,
  };
};
